name: "Learning Go CI"
on:
  push:
    branches: [ main ]

jobs:
  build:
  
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: 1.18
    
    - name: Install dependencies for simple-web-server
      working-directory: ./simple-web-server
      run: go get .

    - name: Build simple-web-server
      working-directory: ./simple-web-server
      run: go build -v .

    - name: Test simple-web-server
      working-directory: ./simple-web-server
      run: go test -v ./...

    - name: Install dependencies for go-cli
      working-directory: ./go-cli
      run: go get .

    - name: Build go-cli
      working-directory: ./go-cli
      run: go build -v .

    - name: Test go-cli
      working-directory: ./go-cli
      run: go test -v ./...

    - name: Build Docker image
      shell: bash
      run: |
       docker build -t simple-web-server:latest ./simple-web-server