name: "Learning Go CI"
on:
  push:
    branches: [ main ]

jobs:
  build:
  
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: 1.18
    
    - name: Install dependencies for example-project
      working-directory: ./example-project
      run: go get .

    - name: Build example-project
      working-directory: ./example-project
      run: go build -v .

    - name: Test example-project
      working-directory: ./example-project
      run: go test -v ./...

    - name: Install dependencies for go-cli
      working-directory: ./go-cli
      run: go get .

    - name: Build go-cli
      working-directory: ./go-cli
      run: go build -v .

    - name: Test go-cli
      working-directory: ./go-cli
      run: go test -v ./...